GestionHeuresAbsences/urls.py
from django.urls import path
from . import views

app_name = 'GestionHeuresAbsences'

urlpatterns = [
    path('', views.login_view, name='login'),

    path('eleve/list', views.eleve_list, name='eleve_list'),
    path('eleve/create', views.eleve_create, name='eleve_create'),
    path('eleve/update/<int:id>', views.eleve_update, name='eleve_update'),
    path('eleve/delete/<int:id>', views.eleve_delete, name='eleve_delete'),

    path('absence_list', views.absence_list, name='absence_list'),
    path('absence/create', views.absence_create, name='absence_create'),
    path('absence/update/<int:id>', views.absence_update, name='absence_update'),
    path('absence/delete/<int:id>', views.absence_delete, name='absence_delete'),

    path('justification_list', views.justification_list, name='justification_list'),
    path('justification/create', views.justification_create, name='justification_create'),
    path('justification/update/<int:id>', views.justification_update, name='justification_update'),
    path('justification/delete/<int:id>', views.justification_delete, name='justification_delete'),
    ]

project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('GestionHeuresAbsences.urls')),
    path('admin/', admin.site.urls),
]

templates/layouts/_navbar.html
{% load static %}
<!-- Top Bar -->
<nav class="navbar">
    <style>
        h2{
            text-align: center;
            text-transform: capitalize;
            color: rgb(31, 121, 211);
            font-weight: bold;
            text-decoration: underline;
        }
    </style>
    <h2>GESTION HEURES D'ABSENCE DES ETUDIANTS DE L'ENSEA D' ABIDJAN</h2>
</nav>

templates/layouts/_siderbar.html
{% load static %}
<!-- Left Sidebar -->
<aside id="leftsidebar" class="sidebar">
    <div class="menu">
        <ul class="list">
            <li>
                <div class="user-info">
                    <div class="image"><a href="profile.html"><img src="{% static 'assets/images/télécharger (3).jpeg' %}" alt="User"></a></div>
                    <div class="detail">
                        <h4>ENSEA</h4>
                        <small>Plus qu'une école, un esprit</small>
                    </div>
                </div>
            </li>
            <li><a href="{% url 'GestionHeuresAbsences:eleve_list' %}" ><i class="zmdi zmdi-chart"></i><span>Etudiants</span></a> </li>
             <li><a href="{% url 'GestionHeuresAbsences:absence_list' %}" ><i class="zmdi zmdi-money-box"></i><span>Absences</span></a> </li>
            <li><a href="{% url 'GestionHeuresAbsences:justification_list' %}" ><i class="zmdi zmdi-account-o"></i><span>Justifications</span></a> </li>
            <li><a href="{% url 'GestionHeuresAbsences:login' %}" ><i class="zmdi zmdi-account-o"></i><span>Deconnexion</span></a> </li>
        </ul>
    </div>
</aside>