GestionHeuresAbsences/urls.py
from django.urls import path
from . import views

app_name = 'GestionHeuresAbsences'

urlpatterns = [
    path('', views.login_view, name='login'),

    path('eleve/list', views.eleve_list, name='eleve_list'),
    path('eleve/create', views.eleve_create, name='eleve_create'),
    path('eleve/update/<int:id>', views.eleve_update, name='eleve_update'),
    path('eleve/delete/<int:id>', views.eleve_delete, name='eleve_delete'),

    path('absence_list', views.absence_list, name='absence_list'),
    path('absence/create', views.absence_create, name='absence_create'),
    path('absence/update/<int:id>', views.absence_update, name='absence_update'),
    path('absence/delete/<int:id>', views.absence_delete, name='absence_delete'),

    path('justification_list', views.justification_list, name='justification_list'),
    path('justification/create', views.justification_create, name='justification_create'),
    path('justification/update/<int:id>', views.justification_update, name='justification_update'),
    path('justification/delete/<int:id>', views.justification_delete, name='justification_delete'),
    ]

project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('GestionHeuresAbsences.urls')),
    path('admin/', admin.site.urls),
]

GestionHeuresAbsences/models.py
from django.db import models

# Table Eleve
class Eleve(models.Model):
    CLASSES = [
        ('AS1A', 'AS1A'),
        ('AS1B', 'AS1B'),
        ('AS2A', 'AS2A'),
        ('AS2B', 'AS2B'),
        ('AS3', 'AS3'),
        ('ISE_eco', 'ISE_eco'),
        ('ISE_math', 'ISE_math'),
        ('ISE2A', 'ISE2A'),
        ('ISE2B', 'ISE2B'),
        ('ISE3', 'ISE3'),
    ]
    SEXE = [
        ('Masculin', 'Masculin'),
        ('Feminin', 'Feminin')
    ]

    matricule_E = models.CharField(max_length=50)
    nom_E = models.CharField(max_length=50)
    prenoms_E = models.CharField(max_length=75)
    sexe_E = models.CharField(max_length=10, choices=SEXE)
    classe = models.CharField(max_length=10, choices=CLASSES)


    class Meta:
        verbose_name = ("Eleve")
        verbose_name_plural = ("Eleves")

    def __str__(self):
        return self.matricule_E + '-' + self.nom_E


# Table Absences
class Absence(models.Model):
    date_A = models.DateField(null=True, blank=True)
    nombre_heures_A = models.IntegerField()
    eleve = models.ForeignKey('GestionHeuresAbsences.Eleve', verbose_name=("Eleve"), on_delete=models.CASCADE)

    class Meta:
        verbose_name = ("Absence")
        verbose_name_plural = ("Absences")

    def __int__(self):
        return str(self.date_A) + str(self.nombre_heures_A)


# Table Justifications
class Justification(models.Model):
    JUSTIFICATION = [
        ('CAS DE MALADIE', 'CAS DE MALADIE'),
        ('AUTORISATION ABSENCE', 'AUTORISATION ABSENCE'),
    ]

    date_J = models.DateField(null=True, blank=True)
    duree_J = models.IntegerField(null=True, blank=True)
    Motifs = models.CharField(max_length=50, choices=JUSTIFICATION)
    eleve = models.ForeignKey('GestionHeuresAbsences.Eleve', verbose_name=("Eleve"), on_delete=models.CASCADE)

    class Meta:
        verbose_name = ("Justification")
        verbose_name_plural = ("Justifications")

    def __str__(self):
        return self.Motifs

GestionHeuresAbsences/forms.py
from django.forms import *
from .models import *

class EleveForm(ModelForm):
    class Meta:
        model = Eleve
        fields = ['matricule_E', 'nom_E', 'prenoms_E', 'sexe_E', 'classe']
        widgets = {
            'matricule_E': TextInput(attrs={
                'class': 'form-control form-control-sm form-element',
            }),

            'nom_E': TextInput(attrs={
                'class': 'form-control form-control-sm form-element',
            }),

            'prenoms_E': TextInput(attrs={
                'class': 'form-control form-control-sm form-element',
            }),

            'sexe_E': Select(attrs={
                'class': 'filter-option-inner-inner form-control',
            }),

            'classe': Select(attrs={
                'class': 'filter-option-inner-inner form-control',
            }),

        }


class AbsenceForm(ModelForm):
    class Meta:
        model = Absence
        fields = ['date_A', 'nombre_heures_A','eleve']
        widgets = {

            'date_A': DateInput(attrs={
                'class': 'form-control form-control-sm form-element',
            }),

            'nombre_heures_A': NumberInput(attrs={
                'class': 'form-control form-control-sm form-element',
            }),

            'eleve': Select(attrs={
                'class': 'filter-option-inner-inner form-control',
            }),
        }


class JustificationForm(ModelForm):
    class Meta:
        model = Justification
        fields = ['date_J', 'duree_J', 'Motifs','eleve']
        widgets = {

            'date_J': DateInput(attrs={
                'class': 'form-control form-control-sm form-element',
            }),

            'duree_J': NumberInput(attrs={
                'class': 'form-control form-control-sm form-element',
            }),

            'Motifs': Select(attrs={
                'class': 'filter-option-inner-inner form-control',
            }),

            'eleve': Select(attrs={
                'class': 'filter-option-inner-inner form-control',
            }),

        }

GestionHeuresAbsences/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from .models import *
from django.contrib.auth import authenticate, login

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('eleve/list')
        else:
            # Affiche un message d'erreur si les informations de connexion sont incorrectes
            error_message = "Nom d'utilisateur ou mot de passe incorrect"
            return render(request, 'GestionHeuresAbsences/pages/login.html', {'error_message': error_message})
    else:
        return render(request, 'GestionHeuresAbsences/pages/login.html')

# Eleves
def eleve_list(request):
    eleves = Eleve.objects.all()
    return render(request, 'GestionHeuresAbsences/pages/eleves/list.html', locals())

def eleve_create(request):
    form = EleveForm()
    if request.method == 'POST':
        form = EleveForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('GestionHeuresAbsences:eleve_list')
    return render(request, 'GestionHeuresAbsences/pages/eleves/create.html', locals())

def eleve_update(request, id):
    instance = get_object_or_404(Eleve, id = id)
    form = EleveForm(instance = instance)
    if request.method == 'POST':
        form = EleveForm(request.POST, instance = instance)
        if form.is_valid():
            form.save()
            return redirect('GestionHeuresAbsences:eleve_list')
    return render(request, 'GestionHeuresAbsences/pages/eleves/update.html', locals())

def eleve_delete(request, id):
    instance = get_object_or_404(Eleve, id = id)
    instance.delete()
    return redirect('GestionHeuresAbsences:eleve_list')

# Absences
def absence_list_user(request, eleve_id):
    eleve = get_object_or_404(Eleve, id=eleve_id)
    absences = Absence.objects.filter(absences__id = eleve_id)
    return render(request, 'GestionHeuresAbsences/pages/absences/list_user.html', locals())

def absence_list(request):
    absences = Absence.objects.all()
    return render(request, 'GestionHeuresAbsences/pages/absences/list.html', locals())

def absence_create(request):
    form = AbsenceForm()
    if request.method == 'POST':
        form = AbsenceForm(request.POST)
        if form.is_valid():
            instance = form.save()
            return redirect('GestionHeuresAbsences:absence_list')
    return render(request, 'GestionHeuresAbsences/pages/absences/create.html', locals())

def absence_update(request, id):
    instance = get_object_or_404(Absence, id = id)
    form = AbsenceForm(instance = instance)
    if request.method == 'POST':
        form = AbsenceForm(request.POST, instance = instance)
        if form.is_valid():
            form.save()
            return redirect('GestionHeuresAbsences:absence_list')
    return render(request, 'GestionHeuresAbsences/pages/absences/update.html', locals())

def absence_delete(request, id):
    instance = get_object_or_404(Absence, id = id)
    instance.delete()
    return redirect('GestionHeuresAbsences:absence_list')

# Justification
def justification_list_user(request, eleve_id):
    eleve = get_object_or_404(Eleve, id=eleve_id)
    justifications = Absence.objects.filter(absences__id = eleve_id)
    return render(request, 'GestionHeuresAbsences/pages/justifications/list_user.html', locals())

def justification_list(request):
    justifications = Justification.objects.all()
    return render(request, 'GestionHeuresAbsences/pages/justifications/list.html', locals())


def justification_create(request):
    form = JustificationForm()
    if request.method == 'POST':
        form = JustificationForm(request.POST)
        if form.is_valid():
            instance = form.save()
            return redirect('GestionHeuresAbsences:justification_list')
    return render(request, 'GestionHeuresAbsences/pages/justifications/create.html', locals())

def justification_update(request, id):
    instance = get_object_or_404(Justification, id = id)
    form = JustificationForm(instance = instance)
    if request.method == 'POST':
        form = JustificationForm(request.POST, instance = instance)
        if form.is_valid():
            form.save()
            return redirect('GestionHeuresAbsences:justification_list')
    return render(request, 'GestionHeuresAbsences/pages/justifications/update.html', locals())

def justification_delete(request, id):
    instance = get_object_or_404(Justification, id = id)
    instance.delete()
    return redirect('GestionHeuresAbsences:justification_list')

GestionHeuresAbsences/templates/GestionHeuresAbsences/pages/eleves/create.html
{% extends "GestionHeuresAbsences/base.html" %}
{% block page_content %}
<div class="container-fluid">
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="card">
                <div class="header">
                    <h2><strong>Ajouter un étudiant</strong></h2>
                    <ul class="header-dropdown">
                        <li class="dropdown"> <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <i class="zmdi zmdi-more"></i> </a>
                            <ul class="dropdown-menu dropdown-menu-right">
                                <li><a href="javascript:void(0);">Action</a></li>
                                <li><a href="javascript:void(0);">Another action</a></li>
                                <li><a href="javascript:void(0);">Something else</a></li>
                            </ul>
                        </li>
                        <li class="remove">
                            <a role="button" class="boxs-close"><i class="zmdi zmdi-close"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="body">
                    <form action="{% url 'GestionHeuresAbsences:eleve_create' %}" method="post">
                        {% csrf_token %}
                        <div class="row clearfix">
                            <div class="col-lg-3 col-md-3 col-sm-3 form-control-label">
                                <label for="email_address_2">Matricule de l'étudiant</label>
                            </div>
                            <div class="col-lg-6 col-md-4 col-sm-4">
                                <div class="form-group">
                                    {{form.matricule_E}}
                                    {% for error in form.matricule_E.errors %}
                                        <div class = "invalid-text small mt-1">
                                            {{ error|escape }}
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                         <div class="row clearfix">
                            <div class="col-lg-3 col-md-3 col-sm-3 form-control-label">
                                <label for="email_address_2">Nom de l'étudiant</label>
                            </div>
                            <div class="col-lg-6 col-md-4 col-sm-4">
                                <div class="form-group">
                                    {{form.nom_E}}
                                    {% for error in form.nom_E.errors %}
                                        <div class = "invalid-text small mt-1">
                                            {{ error|escape }}
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                         <div class="row clearfix">
                            <div class="col-lg-3 col-md-3 col-sm-3 form-control-label">
                                <label for="email_address_2">Prénoms de l'étudiant</label>
                            </div>
                            <div class="col-lg-6 col-md-4 col-sm-4">
                                <div class="form-group">
                                    {{form.prenoms_E}}
                                    {% for error in form.prenoms_E.errors %}
                                        <div class = "invalid-text small mt-1">
                                            {{ error|escape }}
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                         <div class="row clearfix">
                            <div class="col-lg-3 col-md-3 col-sm-3 form-control-label">
                                <label for="email_address_2">Sexe de l'étudiant</label>
                            </div>
                            <div class="col-lg-6 col-md-4 col-sm-4">
                                <div class="form-group">
                                    {{form.sexe_E}}
                                    {% for error in form.sexe_E.errors %}
                                        <div class = "invalid-text small mt-1">
                                            {{ error|escape }}
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                         <div class="row clearfix">
                            <div class="col-lg-3 col-md-3 col-sm-3 form-control-label">
                                <label for="email_address_2">Classe de l'étudiant</label>
                            </div>
                            <div class="col-lg-6 col-md-4 col-sm-4">
                                <div class="form-group">
                                    {{form.classe}}
                                    {% for error in form.classe.errors %}
                                        <div class = "invalid-text small mt-1">
                                            {{ error|escape }}
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                        <div class="row clearfix">
                            <div class="col-lg-9 col-md-8 col-sm-8">
                                <div class="form-group  float-right">
                                    <a href="" class="btn btn-sm btn-info">Annuler</a>
                                    <button type="submit" class="btn btn-sm btn-info">Enregister</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock page_content %}

GestionHeuresAbsences/templates/GestionHeuresAbsences/pages/eleves/list.html
{% extends "GestionHeuresAbsences/base.html" %}
{% block page_content %}
<div class="container-fluid">
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="card">
                <div class="header">
                    <h2><strong>Liste des Etudiants</strong></h2>
                    <ul class="header-dropdown">
                        <li class="dropdown"> <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <i class="zmdi zmdi-more"></i> </a>
                            <ul class="dropdown-menu dropdown-menu-right">
                                <li><a href="javascript:void(0);">Action</a></li>
                                <li><a href="javascript:void(0);">Another action</a></li>
                                <li><a href="javascript:void(0);">Something else</a></li>
                            </ul>
                        </li>
                        <li class="remove">
                            <a role="button" class="boxs-close"><i class="zmdi zmdi-close"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="body">
                    <div class="row mb-2">
                        <div class="col-sm-12">
                            <a href="{% url 'GestionHeuresAbsences:eleve_create'%}" class="btn btn-sm btn-info">
                                <i class="zmdi zmdi-plus"></i> Ajouter un Etudiant</a>
                        </div>
                    </div>
                    <div class="row table-responsive ">
                        <table class="table table-striped">
                            <thead>
                                <tr class="table-primary">
                                    <th>Matricule</th>
                                    <th>Nom</th>
                                    <th>Prenoms</th>
                                    <th>Sexe</th>
                                    <th>Classe</th>
                                    <th class="float-right">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for eleve in eleves %}
                                  <tr>
                                      <td>{{eleve.matricule_E}}</td>
                                      <td>{{eleve.nom_E}}</td>
                                      <td>{{eleve.prenoms_E}}</td>
                                      <td>{{eleve.sexe_E}}</td>
                                      <td>{{eleve.classe}}</td>
                                      <td class="float-right">
                                          <a href="{% url 'GestionHeuresAbsences:eleve_update' id=eleve.id %}" class="btn btn-warning btn-sm">Modifier</a>
                                          <a href="{% url 'GestionHeuresAbsences:eleve_delete' id=eleve.id %}" class="btn btn-danger btn-sm">Supprimer</a>
                                      </td>
                                  </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock page_content %}

GestionHeuresAbsences/templates/GestionHeuresAbsences/pages/eleves/update.html
{% extends "GestionHeuresAbsences/base.html" %}
{% block page_content %}
<div class="container-fluid">
    <div class="row clearfix">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="card">
                <div class="header">
                    <h2><strong>Modification Eleve</strong></h2>
                    <ul class="header-dropdown">
                        <li class="dropdown"> <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <i class="zmdi zmdi-more"></i> </a>
                            <ul class="dropdown-menu dropdown-menu-right">
                                <li><a href="javascript:void(0);">Action</a></li>
                                <li><a href="javascript:void(0);">Another action</a></li>
                                <li><a href="javascript:void(0);">Something else</a></li>
                            </ul>
                        </li>
                        <li class="remove">
                            <a role="button" class="boxs-close"><i class="zmdi zmdi-close"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="body">
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="row clearfix">
                            <div class="col-lg-3 col-md-3 col-sm-3 form-control-label">
                                <label for="email_address_2">Matricule de l'étudiant</label>
                            </div>
                            <div class="col-lg-6 col-md-4 col-sm-4">
                                <div class="form-group">
                                    {{form.matricule_E}}
                                    {% for error in form.matricule_E.errors %}
                                        <div class = "invalid-text small mt-1">
                                            {{ error|escape }}
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>

                         <div class="row clearfix">
                            <div class="col-lg-3 col-md-3 col-sm-3 form-control-label">
                                <label for="email_address_2">Nom de l'étudiant</label>
                            </div>
                            <div class="col-lg-6 col-md-4 col-sm-4">
                                <div class="form-group">
                                    {{form.nom_E}}
                                    {% for error in form.nom_E.errors %}
                                        <div class = "invalid-text small mt-1">
                                            {{ error|escape }}
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>

                         <div class="row clearfix">
                            <div class="col-lg-3 col-md-3 col-sm-3 form-control-label">
                                <label for="email_address_2">Prénoms de l'étudiant</label>
                            </div>
                            <div class="col-lg-6 col-md-4 col-sm-4">
                                <div class="form-group">
                                    {{form.prenoms_E}}
                                    {% for error in form.prenoms_E.errors %}
                                        <div class = "invalid-text small mt-1">
                                            {{ error|escape }}
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>

                         <div class="row clearfix">
                            <div class="col-lg-3 col-md-3 col-sm-3 form-control-label">
                                <label for="email_address_2">Sexe de l'étudiant</label>
                            </div>
                            <div class="col-lg-6 col-md-4 col-sm-4">
                                <div class="form-group">
                                    {{form.sexe_E}}
                                    {% for error in form.sexe_E.errors %}
                                        <div class = "invalid-text small mt-1">
                                            {{ error|escape }}
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>

                         <div class="row clearfix">
                            <div class="col-lg-3 col-md-3 col-sm-3 form-control-label">
                                <label for="email_address_2">Classe de l'étudiant</label>
                            </div>
                            <div class="col-lg-6 col-md-4 col-sm-4">
                                <div class="form-group">
                                    {{form.classe}}
                                    {% for error in form.classe.errors %}
                                        <div class = "invalid-text small mt-1">
                                            {{ error|escape }}
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>

                        <div class="row clearfix">
                            <div class="col-lg-9 col-md-8 col-sm-8">
                                <div class="form-group  float-right">
                                    <a href="" class="btn btn-sm btn-info">Annuler</a>
                                    <button type="submit" class="btn btn-sm btn-info">Enregister</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock page_content %}